id: dd83975db95c4274888b8d1545f5bd83
initial_creation_type: ocr
source_metadata:
  volumes:
    0997a8f3778f4656b6a1c0c4a548db83:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: སྨན་འཚོ་བའི་མདོ།
      total_pages: 1182
      volume_number: 111
